-- Basic table for contact form submissions from the landing page.
create table if not exists public.contact_leads (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  organization text,
  message text not null,
  submitted_at timestamptz not null default now()
);

alter table public.contact_leads enable row level security;

drop policy if exists "Allow anon lead inserts" on public.contact_leads;
create policy "Allow anon lead inserts"
on public.contact_leads
for insert
with check (true);
